### PR TITLE
Packaging the code

### PR DESCRIPTION
**Pull request by bachsh**
Hey,

I know it's been a while since you're written the code but I found it very helpful and it was more convenient to package it for installation. It's very basic but does the trick. After merging, you need to update the installation part in the README to point to your repo.

If you want, you can also submit the code to PyPI after merging. I would've done so myself but it's your code so naturally it's your call to make.

### CODE REVIEW

**Comment by hassony2** [comment]
Thank you for the pull request @bachsh, this is useful  ! 
I will make a quick sanity check this week, and then merge it.
Thank you also for removing the useless imports :)

Best,

Yana

**Comment by bachsh** [comment]
Cool! After you merge don't forget to change the URL in the README.

Removal of useless imports is thanks to PyCharm ❤️

**Comment by bachsh** [comment]
Hey Yana,

I fixed an issue with internal imports of the `utils` module. I haven't noticed it before because I only used the `video_transforms` module, and tested the package from inside the project. I now tested the package externally and the imports work properly to my understanding. Apologies

**Comment by FabianHertwig** [comment]
I basically created the same pull request and just then saw that there is already one.
At least I can review this pull request.

In the funtional.py file is an import of cv2. So should opencv-python be in the install_requires part of the setup.py?
https://github.com/bachsh/torch_videovision/blob/master/torchvideotransforms/functional.py
https://github.com/bachsh/torch_videovision/blob/master/setup.py

Cheers,
Fabian

**Comment by bachsh** [comment]
Thanks for the review!

Yes, it should, but in my experience I wasn't able to install opencv-python
using pip. It should be installed using the system package manager (`apt`,
`yum`, `brew` etc.). I added this step to the installation part in the
README. If you were able to install it using pip please update accordingly.

Avi

**Pull request merged**
